apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
spec:
  selector:
    app: k8s-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8088
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8088
  type: LoadBalancer
  